### ISSUE TITLE
CR: Namespaces are needed

### ISSUE THREAD

**Issue by apocarteres** [TopSecretGames/game#12]
Objection:
In terms of improving code quality and readability we need put all modules into corresponding namespaces.

Goal:
1. Create team-wide name space. Let's say: "tsg" (top secret games)
2. Move GameController and related modules to the namespace "tsg/game"
3. Move MapController and related modules  to the namespace "tsg/game/map"
4. Move MoveController and related modules  to the namespace "tsg/game/move"

Example:
```
namespace tsg {
   namespace game {
      class T ...
   }
}
```

**Comment by stavenko** [comment]
Firstly lets create some short global-whole-game-namespace 
e.g.

    namespace tsr{

    namespace map{
    }
    namespace move{
    }
    }

**Comment by apocarteres** [comment]
agree. let me amend description

**Comment by apocarteres** [comment]
done
