### ISSUE TITLE
CR: Need instance to GameController class

### ISSUE THREAD

**Issue by stavenko** [TopSecretGames/game#15]
Objection:
Viewport positioning requires calls of functions:

`Vec2 cocos2d::Lawer::getPosition()`  & `cocos2d::Lawer::setPosition(Vec2)` 

Goal:
Achieve access to `tsg::game::GameController` within `tsg::map::MapController`.
This could be done with:
  * Call Of Constructor of MapController with pointer to GameController Instance;
  * Call of `onInit` this pointer to instance of `GameController`.

**Comment by apocarteres** [comment]
please use "CR" prefix in title to easy filtering CR's from other issues

**Comment by stavenko** [comment]
Hehe.. didn't mention this. ok.

**Comment by apocarteres** [comment]
yeah, just figured it out  either :)
