### ISSUE TITLE
CR: remove Layer from MapController constructor

### ISSUE THREAD

**Issue by asabelnikova** [TopSecretGames/game#49]
I think, that GameController should not inherit cocos2d::Layer. It should just links all controllers with each other.
So. I suggest that each controller (for now lobby and map) create there own scene and layers, when they need.

Goal:
- remove cocos::Layer from MapController constructor
- MapController create it's own scene and pass it to cocos2d::Director by startGame event

**Comment by stavenko** [comment]
This issue is solved by #53

**Comment by apocarteres** [comment]
ok let's close it then
